//1
SELECT trainee.name AS 'trainee name', 
trainee.email AS 'email', 
course.name AS 'course name', 
FROM_UNIXTIME(end, '%D.%M.%Y') AS 'end' 

FROM history INNER JOIN trainee using(trainee_id) 
INNER JOIN course using(course_id) 

WHERE history.end>=UNIX_TIMESTAMP(DATE_ADD(DATE_SUB(CURRENT_DATE, INTERVAL DAYOFMONTH(CURRENT_DATE)-1 DAY), 
INTERVAL -1 MONTH)) 

AND history.end<=UNIX_TIMESTAMP(DATE_SUB(DATE_SUB(DATE_SUB(DATE_SUB(CURRENT_DATE, 
INTERVAL SECOND(CURRENT_DATE)-59 SECOND), 
INTERVAL MINUTE(CURRENT_DATE)-59 MINUTE), 
INTERVAL HOUR(CURRENT_DATE)-23 HOUR), 
INTERVAL DAYOFMONTH(CURRENT_DATE) DAY))

AND history.status=1 

AND course.name='PHP'

//2
SELECT course.name AS 'course name', 
COUNT(course_id) AS 'quantity'

FROM history INNER JOIN course using(course_id)

WHERE history.start>=UNIX_TIMESTAMP(DATE_SUB(DATE_SUB(DATE_SUB(DATE_SUB(CURRENT_DATE, 
INTERVAL SECOND(CURRENT_DATE) SECOND),
INTERVAL MINUTE(CURRENT_DATE) MINUTE), 
INTERVAL HOUR(CURRENT_DATE) HOUR),
INTERVAL DAYOFMONTH(CURRENT_DATE)-1 DAY)) 

AND history.start<=UNIX_TIMESTAMP(DATE_SUB(DATE_ADD(DATE_SUB(DATE_SUB(DATE_SUB(DATE_SUB(CURRENT_DATE, 
INTERVAL SECOND(CURRENT_DATE)-59 SECOND),
INTERVAL MINUTE(CURRENT_DATE)-59 MINUTE), 
INTERVAL HOUR(CURRENT_DATE)-23 HOUR), 
INTERVAL DAYOFMONTH(CURRENT_DATE)-1 DAY), 
INTERVAL 1 MONTH), 
INTERVAL 1 DAY))

AND history.status=1

GROUP BY course_id
